'0.5.0-beta.1':
    run_id: 1
    order:
        - tic_v8
        - tic_v8_extended
        - legacy_survey_dr8
        - panstarrs1
        - supercosmos
        - sdss_dr13_photoobj_primary
        - sdss_dr16_specobj
        - skymapper_dr2
        - kepler_input_10
        - bhm_rm_v0
        - ps1_g18
        - tycho2
        - gaia_qso
        - bhm_csc
        - gaia_dr2_wd_sdss
        - guvcat
        - allwise
        - unwise
        - catwise2020
        - glimpse
        - glimpse360
        - uvotssc1
        - xmm_om_suss_4_1
    exclude:
        - skymapper_gaia
    sample_region:
        - [270., 66.56, 5.] # North CVZ
        - [90., -66.56, 5.] # South CVZ
        - [45.0, 0.0, 5.] # Stripe-82-West
        - [135.0, 1.0, 5.] # eFEDS
        - [315.0, 0.0, 5.] # Stripe-82-East
    key: null
    query_radius: 1.
    schema: catalogdb
    output_table: catalog
    start_node: tic_v8
    debug: true
    log_path: xmatch_{plan}.log
    tables:
        tic_v8:
            ra_column: ra
            dec_column: dec
            pmra_column: pmra
            pmdec_column: pmdec
            is_pmra_cos: true
            parallax_column: plx
            epoch: 2000.0
            join_weight: 0.1
        tic_v8_extended:
            ra_column: ra
            dec_column: dec
            pmra_column: pmra
            pmdec_column: pmdec
            is_pmra_cos: true
            parallax_column: plx
            epoch: 2000.0
        gaia_dr2_source:
            ra_column: ra
            dec_column: dec
            pmra_column: pmra
            pmdec_column: pmdec
            is_pmra_cos: true
            parallax_column: parallax
            epoch: 2015.5
            join_weight: 0.2
            skip: True
        legacy_survey_dr8:
            ra_column: ra
            dec_column: dec
            pmra_column: pmra
            pmdec_column: pmdec
            is_pmra_cos: true
            parallax_column: parallax
            epoch_column: ref_epoch
            skip_phases: [2]
        twomass_psc:
            ra_column: ra
            dec_column: decl
            epoch_column: jdate
            epoch_format: jd
            skip: true
        tycho2:
            ra_column: ramdeg
            dec_column: demdeg
            pmra_column: pmra
            pmdec_column: pmde
            is_pmra_cos: true
            epoch: 2000.0
            has_missing_coordinates: true
        ps1_g18:
            ra_column: ramean
            dec_column: decmean
        catwise2020:
            ra_column: ra_pm
            dec_column: dec_pm
            pmra_column: pmra
            pmdec_column: pmdec
            has_missing_coordinates: true
            epoch: 2015.402 # MJD 57170
            parallax_column: par_pm
            skip_phases: [3]
            query_radius: 3
        guvcat:
            ra_column: ra
            dec_column: dec
            query_radius: 1.5
        sdss_dr13_photoobj_primary:
            ra_column: ra
            dec_column: dec
        sdss_dr16_specobj:
            ra_column: ra
            dec_column: dec
        uvotssc1:
            ra_column: radeg
            dec_column: dedeg
            skip_phases: [3]
            query_radius: 3
        xmm_om_suss_4_1:
            ra_column: ra
            dec_column: dec
            skip_phases: [3]
            query_radius: 3
        kepler_input_10:
            ra_column: kic_ra
            dec_column: kic_dec
        glimpse:
            ra_column: ra
            dec_column: dec
            skip_phases: [3]
            query_radius: 3
        glimpse360:
            ra_column: ra
            dec_column: dec
            skip_phases: [3]
            query_radius: 3
        skymapper_dr2:
            ra_column: raj2000
            dec_column: dej2000
        gaia_qso:
            ra_column: raj2000
            dec_column: dej2000
        bhm_csc:
            ra_column: oir_ra
            dec_column: oir_dec
            query_radius: 2
        gaia_dr2_wd_sdss:
            ra_column: ra
            dec_column: dec
        unwise:
            ra_column: ra
            dec_column: dec
            skip_phases: [3]
            query_radius: 3
        allwise:
            ra_column: ra
            dec_column: dec
            pmra_column: pmra
            pmdec_column: pmdec
            epoch: 2010.5589 # MJD 55400.0
            skip_phases: [3]
            query_radius: 3
        bhm_rm_v0:
            ra_column: ra
            dec_column: dec
        gaia_unwise_agn: # Only for joining.
            join_weight: 0.3
        panstarrs1:
            ra_column: ra
            dec_column: dec
            query_radius: 1
        supercosmos:
            ra_column: ra
            dec_column: dec
            query_radius: 1
    database_options:
        work_mem: '10GB'
        temp_buffers: '10GB'
        maintenance_work_mem: '10GB'

'0.5.0-beta.2':
    base_plan: '0.5.0-beta.1'
    run_id: 2
    order:
        - tic_v8
        - tic_v8_extended
        - legacy_survey_dr8
        - panstarrs1
        - sdss_dr13_photoobj_primary
        - sdss_dr16_specobj
        - skymapper_dr2
        - kepler_input_10
        - bhm_rm_v0
        - ps1_g18
        - tycho2
        - gaia_qso
        - bhm_csc
        - gaia_dr2_wd_sdss
        - guvcat
        - supercosmos
        - bhm_efeds_veto
        - twoqz_sixqz
        - catwise2020
        - allwise
        - glimpse
        - glimpse360
        - uvotssc1
        - xmm_om_suss_4_1
    exclude:
        - skymapper_gaia
    sample_region:
        - [270., 66.56, 5.] # North CVZ
        - [90., -66.56, 5.] # South CVZ
        - [45.0, 0.0, 5.] # Stripe-82-West
        - [135.0, 1.0, 5.] # eFEDS
        - [315.0, 0.0, 5.] # Stripe-82-East
        - [200.0, 32.375, 1.0] # North/South boundary
        - [282.95, 0.18, 5.0] # GG crowded region
    tables:
        legacy_survey_dr8:
            skip_phases: null
        guvcat:
            query_radius: 2.5
        tic_v8_extended:
            query_radius: 2
        bhm_efeds_veto:
            ra_column: plug_ra
            dec_column: plug_dec
        twoqz_sixqz:
            ra_column: ra_degree
            dec_column: dec_degree

'0.5.0':
    base_plan: '0.5.0-beta.2'
    run_id: 3
    sample_region: null
    exclude_nodes:
        - skymapper_gaia
        - tic_v8_extended
    database_options:
        work_mem: '10GB'
        temp_buffers: '5GB'
        maintenance_work_mem: '5GB'
        enable_hashjoin: false
